services:
  - type: web
    name: brunette-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p models
      curl -o models/79999_iter.pth https://we.tl/t-Xo2aFfuRVJ
    startCommand: gunicorn wsgi:app --config gunicorn_config.py
    disk:
      name: model-storage
      mountPath: /opt/render/project/src/models
      sizeGB: 1
